language: php
php:
- 7.4
cache:
  directories:
  - "$HOME/.composer/cache"
notifications:
  email:
    recipients:
    - wpu@hotmail.de
    on_success: change
    on_failure: change
before_script:
- ".ci/scripts/ciRunner.sh -s build -p $TRAVIS_PHP_VERSION"
addons:
  ssh_known_hosts: lupus-code.it
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in .ci/travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: vendor/bin/dep -f./.ci/deploy.php deploy production
  on:
    branch: feature/add-deployment