version: '2.3'
services:
  #======================================================
  # Application
  #======================================================
  app:
    container_name: headless-blog-app
    image: omegacode/jwt-secured-api-web-server:1.2
    ports:
      - 80:80
    volumes:
      - ./composer.json:/var/www/html/composer.json:cached
      - ./.env:/var/www/html/.env:cached
      - ./bin:/var/www/html/bin:cached
      - ./src:/var/www/html/src:cached
      - ./res:/var/www/html/res:cached
      - ./public:/var/www/html/public:cached
      - ./keys:/var/www/html/keys:cached
      - ./conf:/var/www/html/conf:cached
    depends_on:
      - db
  #======================================================
  # Database
  #======================================================
  db:
    container_name: headless-blog-db
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8
    ports:
      - 3306:3306
    volumes:
      - .database:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=application
  #======================================================
  # Adminer
  #======================================================
  adminer:
    image: adminer:latest
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080